import type { NextPage } from "next";
import React from "react";
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react";
import ControleLivro from "../../classes/controle/ControleLivros";
import { Livro } from "../../classes/modelo/Livro";
import Head from 'next/head'
import { Menu } from '../../componentes/Menu'
import ControleEditora from "../../classes/controle/ControleEditora";
import { LinhaLivro } from "../../componentes/LinhaLivro";


const baseURL :string =  "http://localhost:3000/api/livros"


const controleLivro = new ControleLivro()

async function obter () {
    return fetch(baseURL).then(resp => resp.json())
}

async function excluirLivro(codigo:Number) {
    return fetch(baseURL+'/'+codigo,  {
        method: 'DELETE',
    }).then(response => 'ok')
}

export default function LivroLista (){ 
    const [livros, setLivros] = useState<Array<Livro>>([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        setLivros(controleLivro.obterLivros())
        setCarregado(true)
    }, [carregado])

    const excluir = async (codigoLivro:number) => {
        // Ainda tem que implementar a função
        var indexResult = livros.findIndex((x) => x.codEditora === codigoLivro);
        return livros.splice(indexResult, 1);
    }

    /*
    const excluir = async (codigoLivro:Number) => {
        codigoLivro = livro.codigo
        controleLivro.excluir(codigoLivro);
        setCarregado(false)
    }
    */
  
    return (
    <div className="container-fluid">
        <Head>
        <title> Loja Next </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu/>
        <main>
        <h1> Catálogo de Livros </h1>
            <table className="table">
                <thead>
                    <tr>
                        <th>Titulo</th>
                        <th>Resumo</th>
                        <th>Editora</th> 
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody id='semQuebra'>
                {livros.map((livro) => 
                    <LinhaLivro key={livro.codigo}
                        livro={livro} 
                        //excluir = {() => console.log('excluir')}
                        //setCarregado = {() => setCarregado(false)}
                        excluir = {(codigoLivro) => {
                            codigoLivro = livro.codigo
                            controleLivro.excluir(codigoLivro);
                            setCarregado(false)
                            setLivros(livros)
                        }}
                        //codigoLivro = {livro.codigo}
                        //nomeEditora={new ControleEditora().getNomeEditora(livro.codEditora)} 
                    />
                )}   
                </tbody> 
           </table>
        </main>
    </div>
    )
}
